// Mirrors WooshStrategyRegistry.sol. The Strategy struct is returned as a single tuple
// by getStrategy; viem decodes it into an object keyed by the component names below.
const STRATEGY_COMPONENTS = [
  { name: "owner", type: "address" },
  { name: "kind", type: "uint8" },
  { name: "recipient", type: "address" },
  { name: "tokenOut", type: "address" },
  { name: "amountPerPeriod", type: "uint256" },
  { name: "intervalSeconds", type: "uint64" },
  { name: "periodsTotal", type: "uint32" },
  { name: "periodsDone", type: "uint32" },
  { name: "nextRunAt", type: "uint64" },
  { name: "balance", type: "uint256" },
  { name: "status", type: "uint8" },
  { name: "createdAt", type: "uint64" },
] as const;

const STRATEGY_TUPLE = { type: "tuple", components: STRATEGY_COMPONENTS } as const;
const STRATEGY_TUPLE_ARRAY = { type: "tuple[]", components: STRATEGY_COMPONENTS } as const;

export const STRATEGY_REGISTRY_ABI = [
  {
    name: "strategyId",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "owner", type: "address" },
      { name: "salt", type: "uint256" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    name: "create",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "salt", type: "uint256" },
      { name: "kind", type: "uint8" },
      { name: "recipient", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "amountPerPeriod", type: "uint256" },
      { name: "intervalSeconds", type: "uint64" },
      { name: "periodsTotal", type: "uint32" },
    ],
    outputs: [{ name: "id", type: "bytes32" }],
  },
  {
    name: "createPortfolio",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "salt", type: "uint256" },
      { name: "tokens", type: "address[]" },
      { name: "bps", type: "uint16[]" },
      { name: "mode", type: "uint8" },
      { name: "amountPerPeriod", type: "uint256" },
      { name: "sweepThreshold", type: "uint256" },
      { name: "intervalSeconds", type: "uint64" },
      { name: "periodsTotal", type: "uint32" },
    ],
    outputs: [{ name: "id", type: "bytes32" }],
  },
  {
    name: "getPortfolio",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [
      { name: "tokens", type: "address[]" },
      { name: "bps", type: "uint16[]" },
      { name: "mode", type: "uint8" },
      { name: "sweepThreshold", type: "uint256" },
    ],
  },
  {
    name: "releaseForPortfolio",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "sweepForPortfolio",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "bytes32" },
      { name: "amount6", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "fund",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "executePayment",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "releaseForSwap",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "pause",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "resume",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "cancel",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "setExecutor",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "newExecutor", type: "address" }],
    outputs: [],
  },
  {
    name: "transferAdmin",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "newAdmin", type: "address" }],
    outputs: [],
  },
  {
    name: "executor",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "getStrategiesBatch",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "ids", type: "bytes32[]" }],
    outputs: [STRATEGY_TUPLE_ARRAY],
  },
  {
    name: "getStrategy",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [STRATEGY_TUPLE],
  },
  {
    name: "getStrategyIds",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "bytes32[]" }],
  },
  {
    name: "totalStrategies",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "allIds",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "start", type: "uint256" },
      { name: "count", type: "uint256" },
    ],
    outputs: [{ type: "bytes32[]" }],
  },
  {
    type: "event",
    name: "StrategyCreated",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "kind", type: "uint8", indexed: false },
      { name: "recipient", type: "address", indexed: false },
      { name: "tokenOut", type: "address", indexed: false },
      { name: "amountPerPeriod", type: "uint256", indexed: false },
      { name: "intervalSeconds", type: "uint64", indexed: false },
      { name: "periodsTotal", type: "uint32", indexed: false },
      { name: "funded", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PaymentExecuted",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "periodsDone", type: "uint32", indexed: false },
      { name: "nextRunAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SwapReleased",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "tokenOut", type: "address", indexed: false },
      { name: "amountIn", type: "uint256", indexed: false },
      { name: "periodsDone", type: "uint32", indexed: false },
      { name: "nextRunAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PortfolioCreated",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "tokens", type: "address[]", indexed: false },
      { name: "bps", type: "uint16[]", indexed: false },
      { name: "mode", type: "uint8", indexed: false },
      { name: "sweepThreshold", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PortfolioReleased",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "swapShare", type: "uint256", indexed: false },
      { name: "usdcShare", type: "uint256", indexed: false },
      { name: "periodsDone", type: "uint32", indexed: false },
      { name: "nextRunAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PortfolioSwept",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "pulled", type: "uint256", indexed: false },
      { name: "periodsDone", type: "uint32", indexed: false },
      { name: "nextRunAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StrategyStatusChanged",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "status", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StrategyCancelled",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "refunded", type: "uint256", indexed: false },
    ],
  },
] as const;
